### ISSUE TITLE
New option for shared copyright

### ISSUE THREAD

**Issue by ConorIA** [jessexknight/ut-thesis#13]
Hi @jessexknight. Thanks for maintaining this class. One of my dissertation chapters is based on a publication for which the publisher holds the copyright. I am careful to note the specific copyright on the first page of that chapter, as required by the publisher. I _think_ in this case, the general copyright statement on the cover page is incorrect. I would like to append the phrase "except where otherwise noted". Since the copyright statement is baked into the class. I came up with two ways to get around this, and figured I'd share them here; though I admit that the requirement may be an edge case. 

## Option 1 - new class option

My first attempt was to directly address my specific requirement, where I just wanted a brief disclaimer to follow my name. 

```latex
\newcommand\copyrightstatement{{\copyright} Copyright {\@gradyear} by {\@author}}
\DeclareOption{sharedcopyright}{%
    \renewcommand\copyrightstatement{{\copyright} Copyright {\@gradyear} by {\@author}, except where otherwise noted}
}
```

I then replaced the copyright line in the class by `\copyrightstatement`

## Option 2 - a new command

Alternatively, I thought additional flexibility might be desirable. I don't really need it, but I guess there could be a situation where, e.g., I could want to use "Conor Ian" as the author name, but "Conor I." as the copyright name. I tried to come up with a new command that defaults to the value of `\@author` if it is empty.

``` latex
\newcommand*{\copyrightauthor}[1]{%
    \if\relax\detokenize{#1}\relax
        \gdef\@copyrightauthor{\@author}
    \else
        \gdef\@copyrightauthor{#1}
    \fi
}
```

This works great, for instance, if I insert `\copyrightauthor{Conor I. Anderson, except where otherwise noted}` into my main.tex file. The major drawback here is that omitting `\copyrightauthor{}` causes no name to be printed at all (I had hoped it would print the value of `\@author`). I am pushing the limits of my LaTeX knowledge on this one. I note also that I avoided using a new package for this - I am sure there are clean ways to do this with a new package.

**Comment by jessexknight** [comment]
Thanks for this! I think a combination of options 1 and 2, namely replacing [the whole copyright](https://github.com/jessexknight/ut-thesis/blob/master/ut-thesis/ut-thesis.cls#L131) line in `\maketitle` with a macro that can be user-redefined would be most flexible, without cluttering up the class options.

I will try to implement this next couple days.

**Comment by ConorIA** [comment]
Fantastic. I didn't realize it was so easy to set a default value. Cheers.

**Comment by jessexknight** [comment]
Happy to help!

FWIW, I know almost nothing of copyright (and frankly find it sad that copyright is extorted from authors by journals). A deep dive once into the licensing of the ut-thesis class itself only confused me further... So, suffice to say I'm happy to let authors overwrite the default here as needed!
