### ISSUE TITLE
Department Name “Graduate ..."

### ISSUE THREAD

**Issue by samdscar** [jessexknight/ut-thesis#21]
Hi, 
When using the template, I've had SGS request that I remove the word "Graduate" before the department name on the title and abstract pages. 

This is the comment they sent me on that: "Please remove the word ‘Graduate’ from your Department Name on both your Title and Abstract pages. At the moment the template does include the word ‘Graduate’ but we are working with the library to have that corrected."

<img width="650" alt="image" src="https://github.com/jessexknight/ut-thesis/assets/90656619/f65908c9-bf7c-4f64-aa93-f8a0f5609111">

**Comment by samdscar** [comment]
Nevermind. I've realized that somehow I didnt have the lastest version of the cls file. 

The one on github doesnt seem to have the same problem. Sorry

**Comment by jessexknight** [comment]
You beat me to it -- yes, the assumed "_Graduate_ Department of" was removed in v3.0.6 (9485687) and an optional argument was added to `\department` to fully control or remove this string.
