### ISSUE TITLE
Section title of TOC

### ISSUE THREAD

**Issue by n-yoshikawa** [jessexknight/ut-thesis#24]
The default section title generated by `\tableofcontents` is "Contents", but it needs to be "Table of Contents".

Here is the related part of the rejection email from ProQuest.

```
Contents Section:

- This should be changed to Table of Contents
```

It should be solved by renewing `\contentsname`. (cf. https://tex.stackexchange.com/questions/28516/)

For example,
```   
\renewcommand{\contentsname}{Table of Contents}
\tableofcontents
```

**Comment by jessexknight** [comment]
Thanks for this report. Let's see if this is flagged for multiple users via #23. Untile then I will leave the default `\contentsname` in `ut-thesis` for now.

Edit: thanks also for the solution.
