### ISSUE TITLE
The colour of the items in Table of Contents, List of Tables and List of Figures should be black

### ISSUE THREAD

**Issue by JohnGiorgi** [jessexknight/ut-thesis#25]
I was just recently asked for a revision to my thesis submission by SGS because the text in the `\tableofcontents`,  `\listoftables` and `\listoffigures` was red, not black. Looks like it's red because it is hyperlinked to the corresponding section/table/figure. I hacked a fix by defining a new command:

```latext
% Custom command to set hyperlink colors to black
\newcommand{\blacklinks}{\hypersetup{linkcolor=black}}
\newcommand{\defaultlinks}{\hypersetup{linkcolor=red}} % Set this to your default link color
```

and then wrapping my calls to `\tableofcontents`,  `\listoftables` and `\listoffigures` in `main.txt` with it:

```latest
\blacklinks
\tableofcontents
\listoftables
\listoffigures
\defaultlinks
```

**Comment by jessexknight** [comment]
Thanks for logging this issue under #23. I will close it here since this is a feature of [hyperref](https://ctan.org/pkg/hyperref) as you mentioned, and I feel it's out of scope for *ut-thesis* to fiddle with any text colours, as the default is already black.
