### ISSUE TITLE
Chapter name overflow

### ISSUE THREAD

**Issue by zha** [jessexknight/ut-thesis#26]
I have long chapter titles so the headers on each page would overflow. I change the cls file to include only the chapter number but not the titles. 

I think it should be acceptable for SGS? The Word template does not have chapter titles on each after all so...

**Comment by jessexknight** [comment]
Do you know about short titles in LaTeX (in general)?

The example [here](https://tex.stackexchange.com/a/6866/111678) shows how to provide a short version of the chapter (or section) title to appear in the header and/or table of contents.  I confirmed it works in `ut-thesis` but let me know if you have trouble.

**Comment by jessexknight** [comment]
related issue: #9
