### ISSUE TITLE
Page number at the bottom of each page thoughtout 

### ISSUE THREAD

**Issue by sahasud1** [jessexknight/ut-thesis#9]
One of my chapter title is too long and it hides the page number printed at the header. How can I put the page number at the bottom of each page throughout the thesis?

**Comment by jessexknight** [comment]
You can provide a short title to commands like `\chapter` and `\section` using the optional argument in `[*]`

    \chapter[shorter title]{very long title}

More information [here](https://tex.stackexchange.com/questions/26234). This behaviour is from the `book` class on which `ut-thesis` is based (I think all standard LaTeX classes have something similar).

If you want to remove chapter titles and the just use page numbers at the bottom (no header), then you can use:

    \pagestyle{plain}

However, if you want to move the page numbers from the current headers and place the centre bottom, its a bit more involved. Will post code here in a moment.

**Comment by jessexknight** [comment]
This will achieve exactly what you wanted but as you can see it's a bit messy... You can put it anywhere before `\begin{document}`
```latex
\makeatletter
\if@twoside
\renewcommand*{\ps@headings}%
  {\let\@mkboth\markboth
   \def\@oddfoot{\hfil\thepage\hfil}
   \def\@evenfoot{\hfil\thepage\hfil}
   \def\@oddhead{\headerstyle{\rightmark\hfil}}%
   \def\@evenhead{\headerstyle{\hfil\leftmark}}%
   \def\chaptermark##1{\markboth{%
     \if@mainmatter\headerstyle{\@chapapp\ \thechapter.\ ##1}\fi}{}}
   \def\sectionmark##1{\markright{%
     \if@mainmatter\headerstyle{\thesection.\ ##1}\fi}}}
\else
\renewcommand*{\ps@headings}%
  {\let\@mkboth\markboth
   \def\@oddfoot{\hfil\thepage\hfil}
   \def\@evenfoot{\hfil\thepage\hfil}
   \def\@oddhead{\headerstyle{\rightmark\hfil}}%
   \def\chaptermark##1{\markright{%
     \if@mainmatter\headerstyle{\@chapapp\ \thechapter.\ ##1}\fi}}}
\fi
\makeatother
```

**Comment by sahasud1** [comment]
Thanks, I have been using the `\chapter` optional argument in `[*]`, but still wanted to see if there is any better solutions.

For the code you provided, where exactly you want me to copy the code? I guess it should be somewhere in the `ut-thesis.cls`?

**Comment by jessexknight** [comment]
Personally I think the optional short title is the best solution. Is your chapter title just long enough that the page number is an issue, or does it also extend into the margin? If it extends into the margin, then the newline location could be specified in the short title (though even then, I haven't ever seen any document with line wrapping header) as such a newline should not be included in the main (non-optional) chapter title, which I think would also affect the table of contents.

To answer your question if you prefer the new code, you can put it anywhere in the preamble - i.e. between `\documentclass` and `\begin{document}`. Personally, I tend to put such ugly configuration code in another small file and include it with `\input{config}` somewhere in the preamble.
